---
title: "EyeTracking"
author: "Dana Jensen"
date: "February 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
#preamble
setwd("C:/Users/danaj/OneDrive/Desktop/COMPUTATIONAL MODELLING/ComputationalModelling")
library(pacman)
p_load(readr,groupdata2,tidyverse, modelr, lmerTest, Metrics, lme4, merTools, ggplot2,dplyr, stringr, plyr, data.table, sim, Rmisc, caret, MuMIn, grid, jpeg)
```

PRE-PROCESSING

```{r}

# load data
fix<-read.csv("FixationsV1.csv")
sac<-read.csv("SaccadesV1.csv")
sam<-read.csv("SamplesV1.csv")

log1<- read.csv("logfile_1_2_f.csv")
log2<- read.csv("logfile_2_1_f.csv")
log3<- read.csv("logfile_3_2_f.csv")
log4<- read.csv("logfile_4_1_f.csv")
log5<- read.csv("logfile_5_2_m.csv")
log6<- read.csv("logfile_6_1_m.csv")
 
log<-rbind(log1,log2,log3,log4,log5,log6) 

# clean up
fix$subject = fix$ParticipantID
fix$ParticipantID = NULL

sac$subject = sac$ParticipantID
sac$ParticipantID = NULL

sam$subject = sam$ParticipantID
sam$ParticipantID = NULL

log$Trial = log$X
log$X = NULL

# don't want trial '0'
log$Trial = log$Trial + 1

Fix = merge(log, fix, all = TRUE)
Sac = merge(log, sac, all = TRUE)
Sam = merge(log, sam, all = TRUE)

# match conditions
Fix$SearchType[Fix$SearchOrder == "1" & Fix$Trial < "6"]="Star"
Fix$SearchType[Fix$SearchOrder == "1" & Fix$Trial > "5"]="Count"
Fix$SearchType[Fix$SearchOrder == "2" & Fix$Trial < "6"]="Count"
Fix$SearchType[Fix$SearchOrder == "2" & Fix$Trial > "5"]="Star"
Fix$SearchType[Fix$SearchOrder == "1" & Fix$Trial == "10"]="Count"
Fix$SearchType[Fix$SearchOrder == "2" & Fix$Trial == "10"]="Star"

write.csv(Fix, file = "Fix.csv")

Sac$SearchType[Sac$SearchOrder == "1" & Sac$Trial < "6"]="Star"
Sac$SearchType[Sac$SearchOrder == "1" & Sac$Trial > "5"]="Count"
Sac$SearchType[Sac$SearchOrder == "2" & Sac$Trial < "6"]="Count"
Sac$SearchType[Sac$SearchOrder == "2" & Sac$Trial > "5"]="Star"
Sac$SearchType[Sac$SearchOrder == "1" & Sac$Trial == "10"]="Count"
Sac$SearchType[Sac$SearchOrder == "2" & Sac$Trial == "10"]="Star"

write.csv(Sac, file = "Sac.csv")

Sam$SearchType[Sam$SearchOrder == "1" & Sam$Trial < "6"]="Star"
Sam$SearchType[Sam$SearchOrder == "1" & Sam$Trial > "5"]="Count"
Sam$SearchType[Sam$SearchOrder == "2" & Sam$Trial < "6"]="Count"
Sam$SearchType[Sam$SearchOrder == "2" & Sam$Trial > "5"]="Star"
Sam$SearchType[Sam$SearchOrder == "1" & Sam$Trial == "10"]="Count"
Sam$SearchType[Sam$SearchOrder == "2" & Sam$Trial == "10"]="Star"

write.csv(Sam, file = "Sam.csv")

# let's not clean the data every single time...
Fix <- read.csv("Fix.csv")
Sac <- read.csv("Sac.csv")
Sam <- read.csv("Sam.csv")

# use Riccardo's data in case something went wrong
Fix <- read.csv("FixationsV2.csv")
Sac <- read.csv("SaccadesV2.csv")
Sam <- read.csv("SamplesV2.csv")

Fix$subject = Fix$ParticipantID
Fix$ParticipantID = NULL
```

FIXATION MODELS

```{r}
# load data
logs_fix_V1 = read.csv("FixationsV2.csv")

# try out some models for fun
m <- glmer(Duration ~ SearchType * Trial + (1 + SearchType | ParticipantID), data = logs_fix_V1, family = gaussian(link= log))
summary(m)

m1 <- glmer(Duration ~ SearchType + Trial + (1 + SearchType | ParticipantID), data = logs_fix_V1, family = gaussian(link= log))
summary(m1)

m2 <- glmer(Duration ~ SearchType + (1 + SearchType | ParticipantID), data = logs_fix_V1, family = gaussian(link= log))
summary(m2)

```

FIXATION ANALYSIS

```{r}

#subset to visual search condition
search = subset(logs_fix_V1,Task == "VisualSearch")
search$ParticipantID = as.numeric(as.factor(as.character(search$ParticipantID)))

# fold data for CV
folds=4
foldyFixV2=fold(search, folds, id_col = "ParticipantID")

# create models as strings to use in CV function later
gmod="glmer(Duration~SerachType + Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)"
mod1="glmer(Duration~SearchType * Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)"
mod2="glmer(Duration~SearchType + (1+SearchType |ParticipantID),family = gaussian (link = log), search)"

# list of strings
models=c(gmod,mod1,mod2) 

# create a cross validation function
cross_v=function(numfolds, data, tempmod_string){
  # variables
  foldyFixV2=fold(search, folds, id_col = "ParticipantID")
  perf_test_list=c()
  perf_train_list=c()
  # making train and test data
  for(i in seq(numfolds)){
    temp_train = subset(foldyFixV2, .folds != i)
    temp_test = subset(foldyFixV2, .folds == i)
    temp_model = glmer(Duration~SearchType + Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)
    # appending rmse
    pred_test=predict(temp_model, temp_test, allow.new.levels=T)
    perf_test=Metrics::rmse(temp_test$Duration, pred_test)
    perf_test_list=c(perf_test_list, perf_test)
    pred_train=predict(temp_model, temp_train, allow.new.levels=T)
    perf_train=Metrics::rmse(temp_train$Duration, pred_train)
    perf_train_list=c(perf_train_list, perf_train)
  }
    # save to df
    perf_df= data.frame(perf_test_list, perf_train_list, temp_model=tempmod_string)
}

# loop over models
for(temp_model in models) 
  if (temp_model == models[1]){
    results_df=cross_v(4, foldyFixV2, temp_model)
   }else{
   results_df = rbind(results_df, cross_v(4, foldyFixV2, temp_model))
  }

# getting average test rmse to find best model
try = data.frame(results_df)
try = group_by(try, temp_model) %>%
  summarise_each(funs(mean(. , na.rm= T)), perf_test_list)
try = setnames(try,"perf_test_list", "mean_test_rmse" )

```

MODEL AND PLOTS

```{r}

# using best model on full dataset
best<-glmer(Duration~SearchType * Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)
summary(best)

# plotting duration by trial for visual search task
a<-ggplot(search, aes(x = Trial, y = Duration, fill = Trial)) +
  geom_bar(stat = "identity")+
  facet_grid(~SearchType)

```

SACCADE MODELS

```{r}
# load data
logs_sac_V1 = read.csv("SaccadesV2.csv") 

# try out some models for fun

m1 <- glmer(Amplitude ~ SearchType + (1 + SearchType | ParticipantID), data = logs_sac_V1, family = gaussian(link= log))
summary(m1)

m2 <- glmer(Amplitude ~ SearchType + Trial + (1 + SearchType | ParticipantID), data = logs_sac_V1, family = gaussian(link= log))
summary(m2)

m3 <- glmer(Amplitude ~ SearchType * Trial + (1 + SearchType | ParticipantID), data = logs_sac_V1, family = gaussian(link= log))
summary(m3)

```

SACCADE ANALYSIS

```{r}

#subset to visual search condition
search = subset(logs_sac_V1,Task == "VisualSearch")
search$ParticipantID = as.numeric(as.factor(as.character(search$ParticipantID)))
folds= 4

# fold data for CV
foldySacV2=fold(search, folds, id_col = "ParticipantID")

# create models as strings to use in CV function later
gmod="glmer(Amplitude~SerachType + Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)"
mod1="glmer(Amplitude~SearchType * Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)"
mod2="glmer(Amplitude~SearchType + (1+SearchType |ParticipantID),family = gaussian (link = log), search)"

# list of strings
models=c(gmod,mod1,mod2) 

#Yes I know I could generalize this and not have to re-write it but I am lazy and it is faster to copy and paste #Don'tHateAppreciate

# create a cross validation function
cross_v=function(numfolds, data, tempmod_string){
  # variables
  foldySacV2=fold(search, folds, id_col = "ParticipantID")
  perf_test_list=c()
  perf_train_list=c()
  # making train and test data
  for(i in seq(numfolds)){
    temp_train = subset(foldySacV2, .folds != i)
    temp_test = subset(foldySacV2, .folds == i)
    temp_model = glmer(Amplitude~SearchType + Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)
    # appending rmse
    pred_test=predict(temp_model, temp_test, allow.new.levels=T)
    perf_test=Metrics::rmse(temp_test$Duration, pred_test)
    perf_test_list=c(perf_test_list, perf_test)
    pred_train=predict(temp_model, temp_train, allow.new.levels=T)
    perf_train=Metrics::rmse(temp_train$Duration, pred_train)
    perf_train_list=c(perf_train_list, perf_train)
    }
    # save to df
    perf_df= data.frame(perf_test_list, perf_train_list, temp_model=tempmod_string)
}

# loop over models
for(temp_model in models) 
  if (temp_model == models[1]){
    results_df=cross_v(4, foldySacV2, temp_model)
   }else{
   results_df = rbind(results_df, cross_v(4, foldySacV2, temp_model))
  }

# getting average test rmse to find best model
try = data.frame(results_df)
try = group_by(try, temp_model) %>%
  summarise_each(funs(mean(. , na.rm= T)), perf_test_list)
try = setnames(try,"perf_test_list", "mean_test_rmse" )

```

MODEL AND PLOTS

```{r}

# using best model on full dataset
best2<- glmer(Amplitude~SearchType * Trial + (1+SearchType |ParticipantID),family = gaussian (link = log), search)
summary(best2)

# plotting amplitude by trial for visual search task
b<-ggplot(search, aes(x = Trial, y = Amplitude, fill = Trial)) +
  geom_bar(stat = "identity")+
  facet_grid(~SearchType)

```

VISUALIZATIONS

```{r}

# 1. Jellyfish Heatmap
# set colours
jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))
# load image
img <- readJPEG('eyetrackingscripts/Foraging/ng090ws.jpg')
g <- rasterGrob(img, interpolate=TRUE)

# visual search fixation plot
c<-ggplot(subset(Fix, Task=='VisualSearch' & subject =='6_3_m2' & Trial==6), aes(x = PositionX, y = PositionY)) +
xlim(0,1920) +
ylim(0, 1080) +
annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-0, ymax=1080) +
stat_density2d(geom="raster", aes(fill=..density.., alpha=sqrt(sqrt(..density..))), contour=FALSE, n=1000) + 
scale_alpha(range = c(0.1, 0.6)) + 
scale_fill_gradientn(colours = jet.colors(10), trans="sqrt")

c

# 2. Sheep Heatmap
# load image
img2 <- readJPEG('eyetrackingscripts/foraging/ng049ws.jpg')
g1 = rasterGrob(img2,interpolate=TRUE)

# visual search fixation plot
d = ggplot(subset(Fix, Task=='VisualSearch' & subject =='3_1_f1' & Trial==3), aes(x = PositionX, y = 1081 -PositionY)) +
xlim(0,1920) +
ylim(0, 1080) +
annotation_custom(g1, xmin=-Inf, xmax=Inf, ymin=-0, ymax=1080) +
stat_density2d(geom="raster", aes(fill=..density.., alpha=sqrt(sqrt(..density..))), contour=FALSE, n=1000) + 
scale_alpha(range = c(0.1, 0.6)) + scale_fill_gradientn(colours = jet.colors(10), trans="sqrt")

d

```


```{r}


























```
